version: '3.8'

services:
  postgres:
    container_name: "dogker-postgres"
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - ./.env
    networks:
      - dogker
  authentications:
    container_name: "dogker-authentications"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
      - 4001:4000
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./protos:/app/src
    depends_on:
      - postgres
    networks:
      - dogker
networks:
  dogker:

